name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: echo "Hello World!"

  print_date:
    runs-on: ubuntu-20.04
    steps:
      - name: Print date
        run: date

  print_ls:
    runs-on: ubuntu-20.04
    steps:
      - name: List files
        run: ls -l
